### ISSUE TITLE
Puzzling FROMGIT verification error 

### ISSUE THREAD

**Issue by gwendalcr** [atseanpaul/review-o-matic#10]
In https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1702621:

"""
...
Signed-off-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
(cherry picked from commit eb7ecb5192b2dcf2992f39156aacf72f6e78eae3
 https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git togreg)
...
""""

I get the error message:

"""
The commit hash(es) you've provided in your commit message could not be found
upstream. The following hash/remote/branch tuple(s) were tried:

  eb7ecb5192b2dcf2992f39156aacf72f6e78eae3
    from remote https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git branch togreg

Please double check your commit hash is valid in the upstream tree, and please
fully specify the remote tree and branch for FROMGIT changes (see below):

    (cherry picked from commit <commit SHA>
     <remote git url> <remote git branch>)
"""

But the path does exist:

https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git/commit/?h=togreg&id=eb7ecb5192b2dcf2992f39156aacf72f6e78eae3

**Comment by gwendalcr** [comment]
Running locally, I see the same error:

./troll-o-matic.py --verbose --chatty --git-dir ~/chromiumos/src/third_party/kernel/v4.19 --force-cl 1702621  --dry-run
/usr/local/google/home/gwendal/.local/lib/python3.6/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Force reviewing change  "BACKPORT: FROMGIT: iio: cros_ec: Remove replacing error code with -EIO" (https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1702621)
Processing change https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1702621
Running git -C /usr/local/google/home/gwendal/chromiumos/src/third_party/kernel/v4.19 fetch --prune cros refs/changes/21/1702621/5
Fetching https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git/togreg as gitkernelorgpubscmlinuxkernelgitjic23iiogit
Review for change: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1702621
  Issues: dict_keys([invalid_hash]), Feedback: dict_keys([]), Vote:-1, Notify:True

...


What is happening is the targeted fetch is not fetching:
$ git -C togreg remote add gitkernelorgpubscmlinuxkernelgitjic23iiogit https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git

$ git -C togreg remote show gitkernelorgpubscmlinuxkernelgitjic23iiogit
* remote gitkernelorgpubscmlinuxkernelgitjic23iiogit
  Fetch URL: https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git
  Push  URL: https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git
  HEAD branch: master
  Remote branches:
    compiletest               new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    experimental-beaglefun    new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    fixes-togreg              new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    fixes-togreg-in-a-hurry   new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    ib-iio-mfd-4.9rc1         new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    ib-iio-mfd-4.9rc1-testing new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    ib-iio-mfd-4.9rc1testing  new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    ib-iio-mfd-ti335x_dma     new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    ib-jz47xx-battery-prereq  new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    master                    new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
..
    togreg                    new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
  Local ref configured for 'git push':
    master pushes to master (local out of date)

git -C togreg fetch --prune gitkernelorgpubscmlinuxkernelgitjic23iiogit togreg
warning: no common commits
remote: Counting objects: 2531915, done.
remote: Compressing objects: 100% (420223/420223), done.
remote: Total 2531915 (delta 2093698), reused 2486560 (delta 2086656)
Receiving objects: 100% (2531915/2531915), 540.90 MiB | 6.37 MiB/s, done.
Resolving deltas: 100% (2093698/2093698), done.
From https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio
 * tag               togreg     -> FETCH_HEAD
$ git -C togreg remote show gitkernelorgpubscmlinuxkernelgitjic23iiogit
* remote gitkernelorgpubscmlinuxkernelgitjic23iiogit
  Fetch URL: https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git
  Push  URL: https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git
  HEAD branch: master
  Remote branches:
    compiletest               new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    experimental-beaglefun    new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    fixes-togreg              new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
...
remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    testing2                  new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    togreg                    new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
  Local ref configured for 'git push':
    master pushes to master (local out of date)


When I specify the ref formally, then it works:
$ git -C togreg fetch gitkernelorgpubscmlinuxkernelgitjic23iiogit refs/heads/togreg
warning: no common commits
remote: Counting objects: 6800474, done.
remote: Compressing objects: 100% (1046027/1046027), done.
remote: Total 6800474 (delta 5715695), reused 6784249 (delta 5708146)
Receiving objects: 100% (6800474/6800474), 1.14 GiB | 7.89 MiB/s, done.
Resolving deltas: 100% (5715695/5715695), done.
From https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio
 * branch                    togreg     -> FETCH_HEAD
 * [new branch]              togreg     -> gitkernelorgpubscmlinuxkernelgitjic23iiogit/togreg
$ git -C togreg remote show gitkernelorgpubscmlinuxkernelgitjic23iiogit
* remote gitkernelorgpubscmlinuxkernelgitjic23iiogit
  Fetch URL: https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git
  Push  URL: https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git
  HEAD branch: master
  Remote branches:
    compiletest               new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    experimental-beaglefun    new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    fixes-togreg              new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
 ...
    testing2                  new (next fetch will store in remotes/gitkernelorgpubscmlinuxkernelgitjic23iiogit)
    togreg                    tracked
  Local ref configured for 'git push':
    master pushes to master (local out of date)

**Comment by atseanpaul** [comment]
Hmm, yeah looks like the issue is that if a branch and tag have the same name, git fetches the tag. Thanks for the report, I'll add /refs/heads/ when fetching (and wait for that to break something else :))
