### ISSUE TITLE
Vote flipped after trivial rebase

### ISSUE THREAD

**Issue by terry182** [atseanpaul/review-o-matic#37]
E.g. https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4028479

the difference between Patchset 5 is only the base but the vote flipped from +1 to -1.

**Comment by atseanpaul** [comment]
Looks like f723aa13a39b9063201c8af0c36c227a7380a3bb was introduced in between revisions. This caused some context differences which triggered the -1. If you look at the diff on gerrit, it doesn't match the diff upstream so I think BACKPORT is the right prefix for this.
